import os
import snakemake_tools as tools
import openproblems.api.main

rule all:
    input:
        summary = "{}/../results.json".format(tools.SCRIPTS_DIR),
        website = "{}/website.complete.temp".format(tools.TEMPDIR),

rule website:
    input:
        tasks = [
            "{tempdir}/{task}.task.json".format(tempdir=tools.TEMPDIR, task=task)
            for task in openproblems.api.main.main(['tasks'], print=False)
        ]
    output: temp("{}/website.complete.temp".format(tools.TEMPDIR))
    shell: "touch {output}"

rule docker:
    input: tools.push_images

rule docker_pull_or_build:
    input: tools.image_markers

rule docker_build:
    input: tools.build_images

rule build_docker_image:
    input:
        dockerfile = "../docker/{image}/Dockerfile",
        requirements = tools.docker_requirements,
    output:
        "../docker/{image}/.docker_build"
    params:
        sourcedir = os.path.dirname(tools.SCRIPTS_DIR),
        user = "singlecellopenproblems"
    shell:
        """docker build -f {input.dockerfile} -t {params.user}/{wildcards.image} .. \
        && touch {output}"""

rule password_docker:
    output:
        filename = temp(".docker_password")
    run:
        with open(output.filename, 'w') as handle:
            handle.write(tools.DOCKER_PASSWORD)

rule login_docker:
    input:
        ".docker_password"
    output:
        temp(".docker_login")
    shell:
        """docker login --username=singlecellopenproblems --password=$(cat {input}) && \
        touch {output}"""

rule push_docker_image:
    input:
        build = "../docker/{image}/.docker_build",
        login = ".docker_login",
    output:
        "../docker/{image}/.docker_push"
    shell:
        "docker push singlecellopenproblems/{wildcards.image} && date +%s > {output}"

rule pull_docker_image:
    output:
        temp("../docker/{image}/.docker_pull")
    shell:
        "docker pull singlecellopenproblems/{wildcards.image} && touch {output}"
