from ..._common.methods.baseline import batch_random_integration
from ..._common.methods.baseline import celltype_random_integration
from ..._common.methods.baseline import no_integration
from ..._common.methods.baseline import random_integration
from ...batch_integration_graph.methods.baseline import celltype_random_graph
from ...batch_integration_graph.methods.combat import combat_full_scaled
from ...batch_integration_graph.methods.combat import combat_full_unscaled
from ...batch_integration_graph.methods.combat import combat_hvg_scaled
from ...batch_integration_graph.methods.combat import combat_hvg_unscaled
from ...batch_integration_graph.methods.fastmnn import fastmnn_embed_full_scaled
from ...batch_integration_graph.methods.fastmnn import fastmnn_embed_full_unscaled
from ...batch_integration_graph.methods.fastmnn import fastmnn_embed_hvg_scaled
from ...batch_integration_graph.methods.fastmnn import fastmnn_embed_hvg_unscaled
from ...batch_integration_graph.methods.harmony import harmony_full_scaled
from ...batch_integration_graph.methods.harmony import harmony_full_unscaled
from ...batch_integration_graph.methods.harmony import harmony_hvg_scaled
from ...batch_integration_graph.methods.harmony import harmony_hvg_unscaled
from ...batch_integration_graph.methods.liger import liger_full_unscaled
from ...batch_integration_graph.methods.liger import liger_hvg_unscaled
from ...batch_integration_graph.methods.mnn import mnn_full_scaled
from ...batch_integration_graph.methods.mnn import mnn_full_unscaled
from ...batch_integration_graph.methods.mnn import mnn_hvg_scaled
from ...batch_integration_graph.methods.mnn import mnn_hvg_unscaled
from ...batch_integration_graph.methods.scanorama import scanorama_embed_full_scaled
from ...batch_integration_graph.methods.scanorama import scanorama_embed_full_unscaled
from ...batch_integration_graph.methods.scanorama import scanorama_embed_hvg_scaled
from ...batch_integration_graph.methods.scanorama import scanorama_embed_hvg_unscaled
from ...batch_integration_graph.methods.scanorama import scanorama_feature_full_scaled
from ...batch_integration_graph.methods.scanorama import scanorama_feature_full_unscaled
from ...batch_integration_graph.methods.scanorama import scanorama_feature_hvg_scaled
from ...batch_integration_graph.methods.scanorama import scanorama_feature_hvg_unscaled
from ...batch_integration_graph.methods.scanvi import scanvi_full_unscaled
from ...batch_integration_graph.methods.scanvi import scanvi_hvg_unscaled
from ...batch_integration_graph.methods.scvi import scvi_full_unscaled
from ...batch_integration_graph.methods.scvi import scvi_hvg_unscaled
from .baseline import celltype_random_embedding
from .baseline import celltype_random_embedding_jitter
from .baseline import no_integration_batch
from .scalex import scalex_full
from .scalex import scalex_hvg
