from .bbknn import bbknn_full_unscaled, bbknn_full_scaled, bbknn_hvg_unscaled, bbknn_hvg_scaled
from .combat import combat_full_unscaled, combat_full_scaled, combat_hvg_unscaled, combat_hvg_scaled
from .desc import desc_full_unscaled, desc_hvg_unscaled, desc_hvg_scaled, desc_full_scaled
from .mnn import mnn_full_unscaled, mnn_hvg_unscaled, mnn_hvg_scaled, mnn_full_scaled
from .saucie_embed import saucie_embed_full_unscaled, saucie_embed_hvg_unscaled, saucie_embed_hvg_scaled, saucie_embed_full_scaled
from .saucie_full import saucie_feature_full_unscaled, saucie_feature_hvg_unscaled, saucie_feature_hvg_scaled, saucie_feature_full_scaled
from .scanorama_embed import scanorama_embed_full_unscaled, scanorama_embed_hvg_unscaled, scanorama_embed_hvg_scaled, scanorama_embed_full_scaled
from .scanorama_full import scanorama_feature_full_unscaled, scanorama_feature_hvg_unscaled, scanorama_feature_hvg_scaled, scanorama_feature_full_scaled
#from .scgen import *
from .scvi import scvi_full_unscaled, scvi_full_scaled, scvi_hvg_unscaled, scvi_hvg_scaled
from .fastmnn_embed import fastmnn_embed_full_unscaled, fastmnn_embed_full_scaled, fastmnn_embed_hvg_scaled, fastmnn_embed_hvg_unscaled
from .fastmnn_feature import fastmnn_feature_full_unscaled, fastmnn_feature_full_scaled, fastmnn_feature_hvg_unscaled, fastmnn_feature_hvg_scaled
from .harmony import harmony_full_unscaled, harmony_full_scaled, harmony_hvg_unscaled, harmony_hvg_scaled
from .liger import liger_full_unscaled, liger_full_scaled, liger_hvg_scaled, liger_hvg_unscaled
from .seurat_full import seurat_full_unscaled, seurat_hvg_unscaled, seurat_full_scaled, seurat_hvg_scaled
from .seuratrpca import seuratrpca_full_unscaled, seuratrpca_full_scaled, seuratrpca_hvg_unscaled, seuratrpca_hvg_scaled
