#!/bin/bash

repository="openproblems-bio/openproblems"
version="b25109b542107847f1f440e21e8f853138f3f010"
component="project/create_component"

cache_dir="$HOME/.cache/openproblems/repos/$repository"
executable_path="target/executable/${component}/$(basename ${component})"
version_file="$HOME/.cache/openproblems/versions/${repository}/${component}/version.txt"

function get_repository {
  if [ ! -d "$cache_dir" ]; then
    mkdir -p "$cache_dir"
    git clone https://github.com/${repository}.git "$cache_dir" > /dev/null
  fi
}

function update_repository {
  (cd "$cache_dir" && \
    git fetch > /dev/null 2>&1 && \
    git checkout "$version" > /dev/null 2>&1 && \
    git pull > /dev/null 2>&1)
}

function pull_image_if_version_changed {
  if [ ! -d "$(dirname $version_file)" ]; then
    mkdir -p "$(dirname $version_file)"
  fi
  if [ ! -f "$version_file" ] || [ "$(cat $version_file)" != "$version" ]; then
    "${cache_dir}/${executable_path}" ---setup pull
    echo "$version" > "$version_file"
  fi
}

get_repository
update_repository
pull_image_if_version_changed

# run the executable
"${cache_dir}/${executable_path}" $@
