from . import denoising
from . import dimensionality_reduction
from . import label_projection
from . import multimodal_data_integration
from . import regulatory_effect_prediction
from . import spatial_decomposition
from ._batch_integration import batch_integration_embed
from ._batch_integration import batch_integration_feature
from ._batch_integration import batch_integration_graph
