from . import denoising
from . import dimensionality_reduction
from . import label_projection
from . import matching_modalities
from . import regulatory_effect_prediction
from . import spatial_decomposition
from ._batch_integration import batch_integration_embed
from ._batch_integration import batch_integration_feature
from ._batch_integration import batch_integration_graph
from ._cell_cell_communication import cell_cell_communication_ligand_target
from ._cell_cell_communication import cell_cell_communication_source_target
