from .alra import alra
from .baseline import no_denoising
from .baseline import perfect_denoising
from .dca import dca
from .knn_smoothing import knn_smoothing
from .magic import knn_naive
from .magic import magic
from .magic import magic_approx
from .magic import magic_approx_reverse_norm
from .magic import magic_reverse_norm
