from .alra import alra_log
from .alra import alra_sqrt
from .baseline import no_denoising
from .baseline import perfect_denoising
from .dca import dca
from .knn_smoothing import knn_smoothing
from .magic import knn_naive
from .magic import magic
from .magic import magic_approx
